spring.application.name=lab8_6733800371_sec1

spring.datasource.url=jdbc:postgresql://localhost:5432/lab8pcp
spring.datasource.username=postgres
spring.datasource.password=m0712

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false
server.port=8080
